# Generated by Django 6.0 on 2026-01-26 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Resumo do conteúdo da aula')),
                ('codigo_embed', models.TextField(help_text='Cole aqui o código Iframe do Panda Video ou Vimeo')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Ordem de exibição na lista')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.livro')),
                ('pagina_referencia', models.ForeignKey(blank=True, help_text='Se este vídeo explica uma página específica, selecione-a aqui.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos_relacionados', to='core.pagina')),
            ],
            options={
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
