# Generated by Django 6.0 on 2026-01-27 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_videoaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='versao_professor_relacionada',
            field=models.OneToOneField(blank=True, help_text='Se este é um livro do aluno, selecione aqui a versão do professor correspondente.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versao_aluno', to='core.livro'),
        ),
    ]
