# Generated by Django 6.0 on 2026-01-29 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_livro_versao_professor_relacionada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoaula',
            options={'ordering': ['-criado_em', 'ordem']},
        ),
        migrations.AlterField(
            model_name='videoaula',
            name='codigo_embed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='videoaula',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videoaula',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='core.livro'),
        ),
        migrations.AlterField(
            model_name='videoaula',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='videoaula',
            name='pagina_referencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pagina'),
        ),
    ]
