# Generated by Django 6.0 on 2026-02-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_videoaula_options_alter_videoaula_codigo_embed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoaula',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_videos/'),
        ),
    ]
