# Generated by Django 6.0 on 2026-02-16 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tokencadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokencadastro',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.escola'),
        ),
        migrations.AddField(
            model_name='tokencadastro',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.turma'),
        ),
    ]
