# Generated by Django 6.0 on 2026-02-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tokencadastro_escola_tokencadastro_turma'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Marque esta opção para liberar este livro para contas de demonstração.'),
        ),
        migrations.AlterField(
            model_name='tokencadastro',
            name='tipo_usuario',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('GESTOR_LOCAL', 'Gestor Escolar'), ('DEMO', 'Conta de Demonstração')], max_length=20),
        ),
    ]
