# Generated by Django 6.0 on 2026-02-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_livro_is_demo_alter_tokencadastro_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokencadastro',
            name='tipo_usuario',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('GESTOR_LOCAL', 'Gestor Escolar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('GESTOR_LOCAL', 'Gestor Local'), ('GESTOR_GERAL', 'Gestor Geral'), ('ADMIN', 'Administrador'), ('DEMO', 'Conta de Demonstração')], default='ALUNO', max_length=20),
        ),
    ]
