# Generated by Django 6.0 on 2026-02-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sessaochat_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='colecao',
            field=models.CharField(blank=True, default='Coleção Principal', max_length=100, null=True, verbose_name='Coleção'),
        ),
    ]
