# Generated by Django 6.0 on 2026-02-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_livro_colecao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Coleção')),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
            },
        ),
        migrations.AddField(
            model_name='livro',
            name='tags',
            field=models.CharField(blank=True, help_text='Digite as palavras-chave separadas por vírgula (ex: matemática, 7º ano, lógica)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='colecao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='core.colecao', verbose_name='Coleção'),
        ),
    ]
