# Generated by Django 6.0 on 2026-02-21 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_colecao_livro_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='colecao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='core.colecao', verbose_name='Coleção'),
        ),
    ]
