# Generated by Django 6.0 on 2026-02-22 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_livro_colecao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colecao',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Coleção', 'verbose_name_plural': 'Coleções'},
        ),
        migrations.AddField(
            model_name='colecao',
            name='ordem',
            field=models.IntegerField(default=0, help_text='Define qual coleção aparece primeiro na estante (números menores aparecem antes).'),
        ),
        migrations.AddField(
            model_name='livro',
            name='volume',
            field=models.PositiveIntegerField(blank=True, help_text='Número do volume (deixe em branco se for volume único).', null=True, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='colecao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='core.colecao', verbose_name='Coleção'),
        ),
        migrations.AddConstraint(
            model_name='livro',
            constraint=models.UniqueConstraint(fields=('colecao', 'volume'), name='unique_volume_por_colecao'),
        ),
    ]
