# Generated by Django 6.0 on 2026-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_colecao_options_colecao_ordem_livro_volume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaochat',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
