# Generated by Django 6.0 on 2026-03-06 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sessaochat_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcessoDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=255, null=True)),
                ('dispositivo', models.CharField(blank=True, max_length=255, null=True)),
                ('data_login', models.DateTimeField(auto_now_add=True)),
                ('ultima_atividade', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acessos_demo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
