# Generated by Django 6.0 on 2026-06-11 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_jogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstatisticasUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao_geral', models.FloatField(default=0.0)),
                ('pontuacao_habilidades', models.JSONField(blank=True, default=dict)),
                ('dias_ofensiva', models.IntegerField(default=0)),
                ('maior_ofensiva', models.IntegerField(default=0)),
                ('ultima_jogada', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SessaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0.0)),
                ('tempo_jogo', models.FloatField(default=0.0)),
                ('codigo_habilidade', models.CharField(blank=True, max_length=50, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='core.jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_jogos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
