# Generated by Django 6.0 on 2026-06-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_estatisticasusuario_sessaojogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaojogo',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='sessaojogo',
            unique_together={('user', 'jogo')},
        ),
    ]
