# Generated by Django 6.0 on 2026-06-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sessaojogo_atualizado_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadeBNCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: EF01MA01', max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('ano_escolar', models.IntegerField(help_text='Ano escolar correspondente (ex: 1 para 1º Ano)')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessaojogo',
            name='codigo_habilidade',
        ),
        migrations.AddField(
            model_name='sessaojogo',
            name='habilidades',
            field=models.JSONField(blank=True, default=dict, help_text="Ex: {'EF01MA01': 10, 'EF02MA01': 5}"),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_escolar',
            field=models.IntegerField(blank=True, help_text='Ano escolar (ex: 1 para 1º Ano, 2 para 2º Ano, etc.)', null=True),
        ),
    ]
