# Generated by Django 6.0 on 2026-07-23 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_habilidadebncc_remove_sessaojogo_codigo_habilidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='caminho_s3',
            field=models.CharField(blank=True, help_text='Caminho base do livro interativo no S3', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='formato',
            field=models.CharField(choices=[('ESTATICO', 'Estático'), ('INTERATIVO', 'Interativo')], default='ESTATICO', max_length=20),
        ),
        migrations.CreateModel(
            name='SessaoLivroInterativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_pagina_visitada', models.IntegerField(default=1)),
                ('respostas_atividades', models.JSONField(blank=True, default=dict)),
                ('tentativas_atividades', models.JSONField(blank=True, default=dict)),
                ('pontuacao', models.FloatField(default=0.0)),
                ('tempo_gasto', models.FloatField(default=0.0)),
                ('habilidades', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_interativas', to='core.livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_livros_interativos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'livro')},
            },
        ),
    ]
