# Generated by Django 6.0 on 2026-07-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_livro_caminho_s3_livro_formato_sessaolivrointerativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaolivrointerativo',
            name='progresso',
            field=models.FloatField(default=0.0),
        ),
    ]
