# Generated by Django 6.0 on 2026-07-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sessaolivrointerativo_progresso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='estatisticasusuario',
            name='pontuacao_eterna',
            field=models.FloatField(default=0.0, help_text='Soma de todas as pontuações adquiridas'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='habilidades_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='jogos', to='core.habilidadebncc'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='rubrica_1',
            field=models.CharField(blank=True, help_text='Rubrica opção 1', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='rubrica_2',
            field=models.CharField(blank=True, help_text='Rubrica opção 2', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='rubrica_3',
            field=models.CharField(blank=True, help_text='Rubrica opção 3', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='rubrica_4',
            field=models.CharField(blank=True, help_text='Rubrica opção 4', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jogo',
            name='rubrica_5',
            field=models.CharField(blank=True, help_text='Rubrica opção 5', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='ano_ensino',
            field=models.IntegerField(blank=True, help_text='Ano escolar correspondente (ex: 1 para 1º Ano)', null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='rubricas_atividades',
            field=models.JSONField(blank=True, default=dict, help_text='Estrutura de rubricas das atividades (usado para livros interativos)'),
        ),
        migrations.AddField(
            model_name='sessaojogo',
            name='recorde_pontuacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sessaolivrointerativo',
            name='recorde_pontuacao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='cidades_gestao',
            field=models.ManyToManyField(blank=True, help_text='Para Gestor Regional gerenciar cidades', to='core.cidade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('GESTOR_LOCAL', 'Gestor Escolar'), ('GESTOR_REGIONAL', 'Gestor Regional'), ('GESTOR_KAIZO', 'Gestor Kaizo'), ('ADMIN', 'Administrador'), ('DEMO', 'Conta de Demonstração')], default='ALUNO', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='estados_gestao',
            field=models.ManyToManyField(blank=True, help_text='Para Gestor Regional/Kaizo gerenciar estados', to='core.estado'),
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='estado',
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estado'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
        migrations.AddField(
            model_name='user',
            name='paises_gestao',
            field=models.ManyToManyField(blank=True, help_text='Para Gestor Kaizo gerenciar países', to='core.pais'),
        ),
    ]
