# Generated by Django 6.0 on 2026-07-26 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_estado_pais_estatisticasusuario_pontuacao_eterna_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número da atividade (ex: 1 para Atividade 1)')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='core.livro')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('livro', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='RubricaAlternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.CharField(help_text='Ex: A, B, C, D', max_length=10)),
                ('texto_rubrica', models.CharField(blank=True, max_length=500, null=True)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubricas', to='core.atividadelivro')),
            ],
            options={
                'ordering': ['alternativa'],
                'unique_together': {('atividade', 'alternativa')},
            },
        ),
    ]
