# Generated by Django 6.0 on 2026-08-03 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_atividadelivro_rubricaalternativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilidadebncc',
            name='exemplo_uso',
            field=models.TextField(blank=True, help_text='Exemplo de uso da habilidade', null=True),
        ),
        migrations.AddField(
            model_name='habilidadebncc',
            name='explicacao',
            field=models.TextField(blank=True, help_text='Explicação da habilidade', null=True),
        ),
        migrations.AlterField(
            model_name='habilidadebncc',
            name='ano_escolar',
            field=models.CharField(help_text='Ano escolar correspondente (ex: 1ANO)', max_length=20),
        ),
        migrations.AlterField(
            model_name='habilidadebncc',
            name='descricao',
            field=models.TextField(help_text='Descrição da habilidade'),
        ),
    ]
