# Generated by Django 6.0 on 2026-08-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_habilidadebncc_exemplo_uso_habilidadebncc_explicacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='habilidades_relacionadas',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.habilidadebncc'),
        ),
    ]
