# Generated by Django 6.0 on 2026-08-05 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_livro_habilidades_relacionadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: 1 Ano EF, 1 Ano EM', max_length=20, unique=True)),
                ('ordem', models.IntegerField(default=0, help_text='Define a ordenação nas listas (ex: 1 para 1º EF, 10 para 1º EM)')),
            ],
            options={
                'verbose_name': 'Ano Escolar',
                'verbose_name_plural': 'Anos Escolares',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterField(
            model_name='habilidadebncc',
            name='ano_escolar',
            field=models.CharField(help_text='Ano escolar correspondente (ex: 1ANO) - OBSOLETO', max_length=20),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano_ensino',
            field=models.IntegerField(blank=True, help_text='Ano escolar correspondente (ex: 1 para 1º Ano) - OBSOLETO', null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='ano_escolar',
            field=models.IntegerField(blank=True, help_text='Ano escolar (ex: 1 para 1º Ano, 2 para 2º Ano, etc.) - OBSOLETO', null=True),
        ),
        migrations.AddField(
            model_name='habilidadebncc',
            name='anos_escolares',
            field=models.ManyToManyField(blank=True, related_name='habilidades', to='core.anoescolar'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='anos_escolares',
            field=models.ManyToManyField(blank=True, related_name='jogos', to='core.anoescolar'),
        ),
        migrations.AddField(
            model_name='livro',
            name='anos_escolares',
            field=models.ManyToManyField(blank=True, related_name='livros', to='core.anoescolar'),
        ),
        migrations.AddField(
            model_name='turma',
            name='ano_escolar_novo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='core.anoescolar'),
        ),
    ]
