# Generated by Django 6.0 on 2026-08-05 19:49

from django.db import migrations

def create_and_migrate_anos(apps, schema_editor):
    AnoEscolar = apps.get_model('core', 'AnoEscolar')
    Turma = apps.get_model('core', 'Turma')
    Livro = apps.get_model('core', 'Livro')
    HabilidadeBNCC = apps.get_model('core', 'HabilidadeBNCC')

    anos_ef = [f"{i} Ano EF" for i in range(1, 10)]
    anos_em = [f"{i} Ano EM" for i in range(1, 4)]
    
    anos_dict = {}
    ordem = 1
    for nome in anos_ef + anos_em:
        ano, _ = AnoEscolar.objects.get_or_create(nome=nome, defaults={'ordem': ordem})
        anos_dict[nome] = ano
        ordem += 1

    # Migrar Turmas
    for turma in Turma.objects.all():
        if turma.ano_escolar:
            nome = f"{turma.ano_escolar} Ano EF"
            if nome in anos_dict:
                turma.ano_escolar_novo = anos_dict[nome]
                turma.save(update_fields=['ano_escolar_novo'])

    # Migrar Livros
    for livro in Livro.objects.all():
        if livro.ano_ensino:
            nome = f"{livro.ano_ensino} Ano EF"
            if nome in anos_dict:
                livro.anos_escolares.add(anos_dict[nome])

    # Migrar Habilidades
    for hab in HabilidadeBNCC.objects.all():
        if hab.ano_escolar:
            # Ex: '1ANO' -> '1', ou '1' -> '1'
            ano_str = str(hab.ano_escolar).replace('ANO', '').strip()
            if ano_str.isdigit():
                nome = f"{ano_str} Ano EF"
                if nome in anos_dict:
                    hab.anos_escolares.add(anos_dict[nome])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_anoescolar_alter_habilidadebncc_ano_escolar_and_more'),
    ]

    operations = [
        migrations.RunPython(create_and_migrate_anos, reverse_code=migrations.RunPython.noop),
    ]
