# Generated by Django 6.0 on 2026-08-05 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_migrate_anos_escolares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habilidadebncc',
            name='ano_escolar',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='ano_ensino',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ano_escolar',
        ),
    ]
