# Generated by Django 6.0 on 2026-08-05 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_habilidadebncc_ano_escolar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='ano_escolar_novo',
            new_name='ano_escolar',
        ),
    ]
