# Generated by Django 6.0 on 2026-08-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_turma_ano_escolar_novo_turma_ano_escolar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaojogo',
            name='rubrica',
            field=models.TextField(blank=True, help_text='Rubrica do jogador nesta sessão', null=True),
        ),
        migrations.AddField(
            model_name='sessaolivrointerativo',
            name='rubrica',
            field=models.TextField(blank=True, help_text='Rubrica do aluno neste livro', null=True),
        ),
    ]
