# Generated by Django 6.0 on 2026-08-22 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_sessaojogo_rubrica_sessaolivrointerativo_rubrica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatisticasusuario',
            name='pontuacao_habilidades',
        ),
        migrations.RemoveField(
            model_name='sessaojogo',
            name='habilidades',
        ),
        migrations.RemoveField(
            model_name='sessaolivrointerativo',
            name='habilidades',
        ),
        migrations.CreateModel(
            name='EstatisticaHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0.0)),
                ('estatistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_details', to='core.estatisticasusuario')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habilidadebncc')),
            ],
            options={
                'unique_together': {('estatistica', 'habilidade')},
            },
        ),
        migrations.AddField(
            model_name='estatisticasusuario',
            name='habilidades_conquistadas',
            field=models.ManyToManyField(related_name='estatisticas_usuario', through='core.EstatisticaHabilidade', to='core.habilidadebncc'),
        ),
        migrations.CreateModel(
            name='SessaoJogoHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0.0)),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habilidadebncc')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_details', to='core.sessaojogo')),
            ],
            options={
                'unique_together': {('sessao', 'habilidade')},
            },
        ),
        migrations.AddField(
            model_name='sessaojogo',
            name='habilidades_conquistadas',
            field=models.ManyToManyField(related_name='sessoes_jogos', through='core.SessaoJogoHabilidade', to='core.habilidadebncc'),
        ),
        migrations.CreateModel(
            name='SessaoLivroHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0.0)),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.habilidadebncc')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_details', to='core.sessaolivrointerativo')),
            ],
            options={
                'unique_together': {('sessao', 'habilidade')},
            },
        ),
        migrations.AddField(
            model_name='sessaolivrointerativo',
            name='habilidades_conquistadas',
            field=models.ManyToManyField(related_name='sessoes_livros', through='core.SessaoLivroHabilidade', to='core.habilidadebncc'),
        ),
    ]
