# Generated by Django 6.0 on 2026-08-22 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_estatisticasusuario_pontuacao_habilidades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estatisticasusuario',
            name='habilidades_conquistadas',
        ),
        migrations.AlterUniqueTogether(
            name='sessaojogohabilidade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessaojogohabilidade',
            name='habilidade',
        ),
        migrations.RemoveField(
            model_name='sessaojogohabilidade',
            name='sessao',
        ),
        migrations.RemoveField(
            model_name='sessaojogo',
            name='habilidades_conquistadas',
        ),
        migrations.AlterUniqueTogether(
            name='sessaolivrohabilidade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessaolivrohabilidade',
            name='habilidade',
        ),
        migrations.RemoveField(
            model_name='sessaolivrohabilidade',
            name='sessao',
        ),
        migrations.RemoveField(
            model_name='sessaolivrointerativo',
            name='habilidades_conquistadas',
        ),
        migrations.DeleteModel(
            name='EstatisticaHabilidade',
        ),
        migrations.DeleteModel(
            name='SessaoJogoHabilidade',
        ),
        migrations.DeleteModel(
            name='SessaoLivroHabilidade',
        ),
    ]
