# Generated by Django 6.0 on 2026-08-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_estatisticasusuario_habilidades_conquistadas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatisticasusuario',
            name='habilidades_conquistadas',
            field=models.ManyToManyField(blank=True, related_name='estatisticas_usuario', to='core.habilidadebncc'),
        ),
        migrations.AddField(
            model_name='sessaojogo',
            name='habilidades_conquistadas',
            field=models.ManyToManyField(blank=True, related_name='sessoes_jogos', to='core.habilidadebncc'),
        ),
        migrations.AddField(
            model_name='sessaolivrointerativo',
            name='habilidades_conquistadas',
            field=models.ManyToManyField(blank=True, related_name='sessoes_livros', to='core.habilidadebncc'),
        ),
    ]
