# Generated by Django 6.0 on 2026-08-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_estatisticasusuario_habilidades_conquistadas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaolivrointerativo',
            name='progresso',
        ),
        migrations.RemoveField(
            model_name='sessaolivrointerativo',
            name='ultima_pagina_visitada',
        ),
    ]
