# Generated by Django 6.0 on 2026-08-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_sessaolivrointerativo_progresso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('caminho_s3', models.CharField(help_text='Caminho base da ferramenta no S3', max_length=500)),
                ('icone', models.CharField(blank=True, default='fas fa-wrench', help_text='Classe de ícone do FontAwesome, ex: fa-solid fa-calculator', max_length=50, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
