# Generated by Django 6.0 on 2026-08-30 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_ferramenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaInterativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('numero_aula', models.PositiveIntegerField(help_text='Número da Aula (ex: 23)')),
                ('capitulo', models.PositiveIntegerField(default=1, help_text='Capítulo ao qual a aula pertence')),
                ('paginas_referencia', models.CharField(blank=True, help_text='Ex: Págs 87 a 89', max_length=100, null=True)),
                ('caminho_s3', models.CharField(help_text='Caminho base da aula no S3 (ex: livros/livro-3/aula-23)', max_length=500)),
                ('tem_desafio', models.BooleanField(default=False, help_text='Marque se a aula possui desafio do explorador')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ano_escolar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aulas_interativas', to='core.anoescolar')),
                ('colecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aulas_interativas', to='core.colecao')),
                ('habilidades_relacionadas', models.ManyToManyField(blank=True, related_name='aulas_interativas', to='core.habilidadebncc')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_interativas', to='core.livro')),
            ],
            options={
                'verbose_name': 'Aula Interativa',
                'verbose_name_plural': 'Aulas Interativas',
                'ordering': ['colecao', 'livro', 'capitulo', 'numero_aula'],
                'unique_together': {('livro', 'numero_aula')},
            },
        ),
    ]
