# Generated by Django 6.0 on 2026-08-30 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_aulainterativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoAulaInterativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0.0)),
                ('recorde_pontuacao', models.FloatField(default=0.0)),
                ('tempo_gasto', models.FloatField(default=0.0)),
                ('rubrica', models.TextField(blank=True, help_text='Rubrica do aluno nesta aula', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_interativas', to='core.aulainterativa')),
                ('habilidades_conquistadas', models.ManyToManyField(blank=True, related_name='sessoes_aulas', to='core.habilidadebncc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_aulas_interativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'aula')},
            },
        ),
        migrations.DeleteModel(
            name='SessaoLivroInterativo',
        ),
    ]
