# Generated by Django 6.0 on 2026-09-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_sessaoaulainterativa_delete_sessaolivrointerativo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ferramenta',
        ),
    ]
