# Generated by Django 6.0 on 2026-09-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_delete_ferramenta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessaoaulainterativa',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sessaoaulainterativa',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='sessaoaulainterativa',
            name='habilidades_conquistadas',
        ),
        migrations.RemoveField(
            model_name='sessaoaulainterativa',
            name='user',
        ),
        migrations.DeleteModel(
            name='AulaInterativa',
        ),
        migrations.DeleteModel(
            name='SessaoAulaInterativa',
        ),
    ]
