# Generated by Django 6.0 on 2026-09-02 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0039_remove_sessaoaulainterativa_aula_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('caminho_s3', models.CharField(help_text='Caminho base do jogo no S3', max_length=500)),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas_jogos/')),
                ('ativo', models.BooleanField(default=True)),
                ('rubrica_1', models.CharField(blank=True, help_text='Rubrica opção 1', max_length=255, null=True)),
                ('rubrica_2', models.CharField(blank=True, help_text='Rubrica opção 2', max_length=255, null=True)),
                ('rubrica_3', models.CharField(blank=True, help_text='Rubrica opção 3', max_length=255, null=True)),
                ('rubrica_4', models.CharField(blank=True, help_text='Rubrica opção 4', max_length=255, null=True)),
                ('rubrica_5', models.CharField(blank=True, help_text='Rubrica opção 5', max_length=255, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anos_escolares', models.ManyToManyField(blank=True, related_name='jogos_novo', to='core.anoescolar')),
                ('habilidades_relacionadas', models.ManyToManyField(blank=True, related_name='jogos_novo', to='core.habilidadebncc')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0.0)),
                ('recorde_pontuacao', models.FloatField(default=0.0)),
                ('tempo_jogo', models.FloatField(default=0.0)),
                ('rubrica', models.TextField(blank=True, help_text='Rubrica do jogador nesta sessão', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('habilidades_conquistadas', models.ManyToManyField(blank=True, related_name='sessoes_jogos_novo', to='core.habilidadebncc')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='jogos.jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_jogos_novo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'jogo')},
            },
        ),
    ]
