# Generated by Django 6.0 on 2026-09-02 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0038_delete_ferramenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Capítulo')),
                ('numero', models.PositiveIntegerField(default=1, verbose_name='Número do Capítulo')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['livro__colecao__ordem', 'livro__volume', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Colecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Coleção')),
                ('ordem', models.IntegerField(default=0, help_text='Define qual coleção aparece primeiro na estante (números menores aparecem antes).')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Coleção',
                'verbose_name_plural': 'Coleções',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='AulaInterativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Aula')),
                ('numero_aula', models.PositiveIntegerField(help_text='Número sequencial da Aula')),
                ('caminho_s3', models.CharField(blank=True, help_text='Caminho base da aula no S3 (ex: livros_web/aula_x)', max_length=500, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anos_escolares', models.ManyToManyField(blank=True, related_name='aulas_interativas_novo', to='core.anoescolar')),
                ('habilidades_bncc', models.ManyToManyField(blank=True, related_name='aulas_interativas_novo', to='core.habilidadebncc')),
                ('capitulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='livros_interativos.capitulo')),
            ],
            options={
                'verbose_name': 'Aula Interativa',
                'verbose_name_plural': 'Aulas Interativas',
                'ordering': ['capitulo__livro__colecao__ordem', 'capitulo__livro__volume', 'capitulo__numero', 'numero_aula'],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Livro')),
                ('volume', models.PositiveIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('capa', models.ImageField(blank=True, help_text='Capa do livro', null=True, upload_to='capas_livros_interativos/')),
                ('ativo', models.BooleanField(default=True)),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='livros_interativos.colecao')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['colecao__ordem', 'volume', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='capitulo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='livros_interativos.livro'),
        ),
        migrations.CreateModel(
            name='SessaoAulaInterativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.FloatField(default=0.0)),
                ('recorde_pontuacao', models.FloatField(default=0.0)),
                ('tempo_gasto', models.FloatField(default=0.0)),
                ('rubrica', models.TextField(blank=True, help_text='Rubrica do aluno nesta aula', null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='livros_interativos.aulainterativa')),
                ('habilidades_conquistadas', models.ManyToManyField(blank=True, related_name='sessoes_aulas_novo', to='core.habilidadebncc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes_aulas_interativas_novo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Aula Interativa',
                'verbose_name_plural': 'Sessões de Aulas Interativas',
                'unique_together': {('user', 'aula')},
            },
        ),
    ]
