# Generated by Django 6.0 on 2026-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Ferramenta')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável (gerado automaticamente se deixado em branco)', max_length=200, unique=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('caminho_s3', models.CharField(help_text='Caminho base da ferramenta no S3 (ex: ferramentas/calculadora)', max_length=500)),
                ('thumb', models.ImageField(blank=True, help_text='Tamanho ideal: 600x400 pixels', null=True, upload_to='ferramentas_thumbs/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ferramenta Kaizo',
                'verbose_name_plural': 'Ferramentas Kaizo',
                'ordering': ['-criado_em'],
            },
        ),
    ]
